import {
  ALTERNATE_NAME,
  ALUMNI_OF,
  AVATAR,
  DESCRIPTION,
  EMPLOYER,
  JOB_TITLE,
  KNOWS_ABOUT,
  LOCATION,
  NAME,
  SITE_URL,
  SOCIAL_LINKS,
} from "./site";

export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": `${SITE_URL}/#person`,
  name: NAME,
  alternateName: ALTERNATE_NAME,
  url: SITE_URL,
  mainEntityOfPage: SITE_URL,
  image: {
    "@type": "ImageObject",
    url: `${SITE_URL}${AVATAR.url}`,
    width: AVATAR.width,
    height: AVATAR.height,
  },
  jobTitle: JOB_TITLE,
  description: DESCRIPTION,
  gender: "Male",
  nationality: { "@type": "Country", name: LOCATION.country },
  address: {
    "@type": "PostalAddress",
    addressLocality: LOCATION.city,
    addressCountry: LOCATION.countryCode,
  },
  worksFor: {
    "@type": "Organization",
    name: EMPLOYER.name,
    url: EMPLOYER.url,
  },
  alumniOf: ALUMNI_OF.map((school) => ({
    "@type": "CollegeOrUniversity",
    name: school,
  })),
  hasOccupation: {
    "@type": "Occupation",
    name: JOB_TITLE,
    occupationLocation: { "@type": "City", name: LOCATION.city },
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "GraphQL",
      "Apollo",
      "Node.js",
      "Express",
      "MongoDB",
      "Redux Toolkit",
      "Storybook",
      "Jest",
      "SCSS",
      "Docker",
    ].join(", "),
  },
  knowsAbout: KNOWS_ABOUT,
  knowsLanguage: ["English", "Ukrainian"],
  sameAs: [SOCIAL_LINKS.linkedin, SOCIAL_LINKS.telegram, SOCIAL_LINKS.instagram],
};

export const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE_URL}/#website`,
  url: SITE_URL,
  name: NAME,
  description: DESCRIPTION,
  inLanguage: "en",
  publisher: { "@id": `${SITE_URL}/#person` },
};
