version: '3.8'

networks:
  app-frontend:
    driver: ${NETWORKS_DRIVER}

volumes:
  nginx-certs:
  nginx-html:
  nginx-vhost:
  acme-state:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    build:
      context: ./docker/nginx-proxy
      args:
        - BASIC_AUTH=${BASIC_AUTH}
        - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
        - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
        - BASIC_AUTH_HOST=${FRONTEND_HOST}
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.nginx-proxy.nginx"
    hostname: ${COMPOSE_PROJECT_NAME}-nginx-proxy
    restart: ${RESTART_POLICY}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-vhost:/etc/nginx/vhost.d
      - ./docker/nginx-proxy/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    networks:
      - app-frontend

  acme-companion:
    image: nginxproxy/acme-companion
    hostname: ${COMPOSE_PROJECT_NAME}-acme-companion
    restart: ${RESTART_POLICY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-vhost:/etc/nginx/vhost.d
      - acme-state:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=${COMPOSE_PROJECT_NAME}-nginx-proxy
    networks:
      - app-frontend
    depends_on:
      - nginx-proxy

  app:
    restart: ${RESTART_POLICY}
    build:
      context: .
      args:
        - API_URL=${API_URL}
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
    hostname: ${COMPOSE_PROJECT_NAME}-fe-app
    environment:
      - VIRTUAL_HOST=${FRONTEND_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${FRONTEND_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - API_URL=${API_URL}
      - GA_ID=${GA_ID}
    networks:
      - app-frontend